    <script type="text/javascript" src="sorttable.js"></script>
  
    <style type="text/css" media="all">
    /*<![CDATA[*/
      #content { 
        width: 80%;
      }
      /* Sortable tables */
      table.sortable a.sortheader {
        background-color:#eee;
        color:#666666;
        font-weight: bold;
        text-decoration: none;
        display: block;
      }
      table.sortable span.sortarrow {
        color: black;
        text-decoration: none;
      }

  /* 
   * Left align table cells by default
   * May overide in page-specific CSS
   */
      th.sortable, 
      td.sortable {
        text-align:left;
      }
    /*]]>*/
    </style>