<?php
/**
* Obsolete
* delete the outdated navigation menu and the files it called
* these files are no longer used at Shoals
*/
?>
<!-- Expects menu.css -->
<div id="menu">
  <!-- about the band-->
  <ul>
    <li>
      <h2>About the band</h2>
      <ul>
        <!-- about detail -->
        <li><a href="index.php" title="Home page">Home page</a></li>
        <li><a href="about.php" title="About the band">Introduction</a></li>
        <li>
          <!-- Organizing documents
          <a href="organization.php" title="Organization of the band" class="x">Organization</a>
          <ul>
            <li><a href="history.php" title="history of the band">History or the Organization</a></li>
            <li><a href="org-docs.php" title="organizing documents">Constitution &amp; Bylaws</a></li>
            <li><a href="board.php" title="Board of Directors">Board of Directors</a></li>
          </ul>
        </li> -->
        
        <!-- funding
        <li><a href="funding.php" title="How we pay for the band">Funding</a></li> -->
        <li><a href="contacts.php" title="How to contact the band">Contact Us</a></li>
        <!-- <li><a href="mail" title="Subscriptions to our mailing lists">Mailing lists</a></li> -->
      </ul>
    </li>
  </ul>

  <!-- about the music-->

  <!-- music libraries -->
  
     <ul>
    <li>
      <h2 id="about_the_music">About the music</h2>
      <ul>
        <li><a href="music-lib-cb.php" title="Concert Music library">Concert Band Library</a></li>
        <!-- <li><a href="music-folder-cb.php" title="Concert Music in Rehearsal">Music in rehearsal</a></li> -->
        <!-- <li><a href="music-wish-cb.php" title="Concert Music Wish List">Concert Band Wish List</a></li> -->
      </ul>
    </li>
  </ul>
  <ul>
    
     
     
   <!-- Scheduling -->
   <!-- Rehearsals -->
   <!--
    <ul>
    <li>
      <h2>Schedule</h2>
      <ul>
        <li><a href=index.php#events title="Next activities for each band">Next events on the schedule</a></li>
        <li><a href=schedule.php title="Scuedule for current season">Schedule for Season</a></li>
        <li><a href="schedule-other.php" title="Other music events submitted by members">Other music events</a></li>
      </ul>
    </li>
  </ul>
  -->
  
  <!-- performances -->

<!--   <ul>
    <li>
      <h2>For Members &amp; Audiences</h2>
      <ul>
        <li><a href="concert-notes.php" title="Concert notes for members">Concert notes</a></li>
        <li><a href="practice-notes.php" title="Guidelines for rehearsals">Rehearsal notes</a></li>
        <li><a href="not-available.php" title="Pictures of the band">Photo Gallery</a></li> 
        <li><a href="not-available.php" title="Subscriptions to our mailing lists">Mailing lists</a></li> 
      </ul>
    </li>
  </ul>
   -->
  <!-- performances -->
  
  <!-- community -->
  
<!--   <ul>
    <li>
      <h2>Community</h2>
      <ul>
        <li><a href="neighbors.php" title="Other bands in our area">Neighbors</a></li>
        <li><a href="links.php" title="External links">Links</a></li>
      </ul><
    </li>
  </ul>
   -->
  <!-- community -->
</div><!-- end of menu -->
